name: Build and deploy to Ansible
run-name: >
  "${{ github.event.head_commit.message }}" ${{ github.event_name }}ed by ${{ github.actor }}

on:
  push:
    branches:
      - production
      - staging
      - kdv/dev
      - tvl/dev
      - rokeppen/githubWorkflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npx browserslist@latest --update-db

      - name: Build frontend
        run: npm run build

      - name: Copy TinyMCE minified files
        run: |
          mkdir -p dist/js
          cp -r node_modules/tinymce/*.min.js node_modules/tinymce/*/ dist/js/ || true

      - name: Create frontend.zip
        run: zip -r frontend.zip dist/*

      - name: Upload zip to Github
        uses: actions/upload-artifact@v5
        with:
          name: frontend-build
          path: frontend.zip

      - name: Activate deploy
        uses: appleboy/ssh-action@v1
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        with:
          proxy_host: ${{ secrets.SSHHOST }}
          proxy_username: ${{ secrets.SSHUSER }}
          proxy_key: ${{ secrets.SSHKEY }}
          proxy_port: ${{ secrets.SSHPORT }}
          host: az-deb-mgmt
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          envs: BRANCH_NAME
          script: |
            echo "Github trigger for branch $BRANCH_NAME"
            sudo -u ansible /opt/deploy-ga.sh frontend ${BRANCH_NAME}